### ISSUE TITLE
Two more papers

### ISSUE THREAD

**Issue by clinicalpersona** [yangkky/Machine-learning-for-proteins#1]
Subject says all... suggest adding these two:

https://academic.oup.com/bioinformatics/search-results?f_Authors=Russ+B+Altman
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0091240

**Comment by raghvendra5688** [comment]
Suggest adding one more to other supervised learning problem:
https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/bty953/5194339?redirectedFrom=fulltext

**Comment by yangkky** [comment]
These are all definitely relevant! Could you either make a pull request or give me a formatted version here that I can copy-paste?

**Comment by yangkky** [comment]
All added.

**Comment by adjvandijk** [comment]
Paper on using random forest to predict protein interactions based on their sequence: https://academic.oup.com/bioinformatics/article/24/1/26/205552
Follow up paper where experimental validation of features (positions in the sequence) with highest feature importance was provided:
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1001017
