### ISSUE TITLE
Where to start?

### ISSUE THREAD

**Issue by dangom** [yangkky/Machine-learning-for-proteins#207]
Sorry if this is a stupid question.
For someone completely new to this field but genuinely curious about it: where to start? I'd assume the reviews, but maybe there are a couple of other influential papers that one should not miss.
Are there 1/2 papers that you'd recommend as an entry point to the field to understand what are the challenges and main questions in the field of ML for proteins / protein design in general?

Feel free to close if too off-topic.

Thank you for putting this together!

**Comment by agitter** [comment]
I saw this while coming here to make a pull request. There are now too many good reviews to pick just one, but I'll do it anyway:

Opportunities and Challenges for Machine Learning-Assisted Enzyme Engineering
https://doi.org/10.1021/acscentsci.3c01275

It's recent, it covers several different (not all) major subproblems, and it's skewed toward one of the problems I'm interested in (enzyme engineering).

Alternatively, skim the titles from the recent GEM workshop to get a broad sense of what people are working on right now: https://openreview.net/group?id=ICLR.cc/2024/Workshop/GEM#tab-accept-oral

**Comment by dangom** [comment]
Hi Anthony, thanks a ton for the answer. Appreciate it.
