### ISSUE TITLE
Add DeepCrystal

### ISSUE THREAD

**Issue by elbasir** [yangkky/Machine-learning-for-proteins#4]
A deep learning framework for protein crystallization prediction
https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/bty953/5194339?redirectedFrom=fulltext

**Comment by yangkky** [comment]
This is definitely relevant! Could you either make a pull request or give me a formatted version here that I can copy-paste?

**Comment by raghvendra5688** [comment]
**DeepCrystal: a deep learning framework for sequence-based protein crystallization prediction**
Abdurrahman Elbasir, Balasubramanian Moovarkumudalvan, Khalid Kunji, Prasanna R Kolatkar, Raghvendra Mall, Halima Bensmail,  Bioinformatics, bty953, https://doi.org/10.1093/bioinformatics/bty953

**Comment by yangkky** [comment]
Added.
