### ISSUE TITLE
suggestion of paper to add to the list

### ISSUE THREAD

**Issue by monasson** [yangkky/Machine-learning-for-proteins#45]
Hello Kevin,

I have just heard about your machine-learning-for-protein list of papers you are maintaining on GitHub, and this is a really nice initiative, useful to the community! Thanks a lot for doing this important work.

I'd like to mention my own paper in the field, published earlier this year in eLife:

Learning protein constitutive motifs from sequence data
J. Tubiana, S. Cocco, R. Monasson, eLife e:39397 (2019)
https://elifesciences.org/articles/39397

which used restricted Boltzmann machines for identifying representations of proteins and generate new sequences. I'd be grateful to you to add it to the list.

best regards,
Remi Monasson, CNRS & Ecole Normale Supérieure, Paris

**Comment by yangkky** [comment]
You're welcome! Thanks for bringing this to my attention.
