### ISSUE TITLE
Protein structure prediction paper by Jinbo Xu

### ISSUE THREAD

**Issue by tmfs10** [yangkky/Machine-learning-for-proteins#6]
https://arxiv.org/pdf/1811.03481.pdf

This is what AlphaFold is based on as well I think

**Comment by yangkky** [comment]
This is definitely relevant! Could you either make a pull request or give me a formatted version here that I can copy-paste?

**Comment by yangkky** [comment]
Added.

**Comment by tmfs10** [comment]
Oops sorry I didn't see this comment but glad it was added!
